# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tobin Yehle
email: tobin.yehle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal site containing personal projects and writing about 
  things I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tobin.yehle.io" # the base hostname & protocol for your site
# twitter_username:
github_username:  tyehle
bitbucket_username: tobinyehle

hidden_posts: ['Python Compiler']

# Build settings
markdown: kramdown
markdown_ext: markdown,mkdown,mkdn,mkd,md
include: ['_pages']

permalink: /articles/:title
