name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - source

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Jekyll Build
        run: |
          bundle config path vendor/bundle  # use a path we can cache
          bundle install
          JEKYLL_ENV=production bundle exec jekyll build
          cd _site
          touch .nojekyll

      # - uses: helaili/jekyll-action@2.0.2
      #   env:
      #     JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
