name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - source

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Jekyll Build
        run: |
          bundle config path vendor/bundle  # use a path we can cache
          bundle install --jobs 4 --retry 3
          JEKYLL_ENV=production bundle exec jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.JEKYLL_PAT }}
          publish_branch: master
          publish_dir: _site
          force_orphan: true

      # - uses: helaili/jekyll-action@2.0.2
      #   env:
      #     JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
